name: Github Actions CICD Test

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      - name: Check out GoCD repository
        run: |
          git clone --branch master git@github.com:memmerson/actions-test actions-test-files
          cd actions-test-files

      - name: Run make build
        run: make build

      - name: Run make test
        run: make test

  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GoCD repository
        run: |
          git clone --branch master git@github.com:memmerson/actions-test actions-test-files
          cd actions-test-files

      - name: Run make test
        run: make test
  
#   deploy_stg:
#   deploy_prf:
#   deploy_prd:
