name: Github Actions CICD Test

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: change directory
        run: cd $GITHUB_WORKSPACE

      - name: Run make build
        run: make build

      - name: Run make test
        run: make test

  deploy_dev:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: Run make deploy_dev
        run: | 
          cd $GITHUB_WORKSPACE
          make deploy_dev
  
  deploy_stg:
    runs-on: ubuntu-latest
    environment: 'stg'
    needs: [deploy_dev]
    steps:
      - uses: actions/checkout@v2

      - name: Run make deploy_stg
        run: | 
          cd $GITHUB_WORKSPACE
          make deploy_stg
  
  deploy_prf:
    runs-on: ubuntu-latest
    environment: 'prf'
    needs: [deploy_stg]
    steps:
      - uses: actions/checkout@v2

      - name: Run make deploy_prf
        run: | 
          cd $GITHUB_WORKSPACE
          make deploy_prf
  
  deploy_prd:
    runs-on: ubuntu-latest
    environment: 'prd'
    needs: [deploy_stg]
    steps:
      - uses: actions/checkout@v2

      - name: Run make deploy_prd
        run: | 
          cd $GITHUB_WORKSPACE
          make deploy_prd
